---
- hosts: db-servers
  become: yes
  become_method: sudo
  connection: ssh
  vars_files:
    - storage.yml
  tasks:
   - name: Add group "ansible" to remote server
     group:
       name: devops
       state: present
   - name: Add users
     user:
       name: "{{ item }}"
       groups: devops,wheel
       shell: /bin/bash
       state: present
       createhome: yes
       system: no 
       password: "{{ my_password | password_hash('sha512') }}"
       update_password: on_create
     loop:
        - alice
        - vincent  
        - titto
  
