---
- hosts: web-servers
  become: true
  tasks:
    - name: Install a .deb package from the internet
      apt:
        deb: http://downloads.datastax.com/cpp-driver/ubuntu/18.04/dependencies/libuv/v1.23.0/libuv1-dev_1.23.0-1_amd64.deb
